language: rust
cache: cargo
rust:
    - stable
    - nightly
script:
    - cd cursive
    - cargo check --all-features
    - cargo build --verbose --features "markdown pancurses-backend termion-backend crossterm-backend"
    - cargo test --verbose --features "markdown pancurses-backend termion-backend crossterm-backend"
