language: rust
cache: cargo
rust:
    - stable
    - nightly
script:
    - cd cursive && cargo check --all-features
    - cd cursive && cargo build --verbose --features "markdown pancurses-backend termion-backend crossterm-backend"
    - cd cursive && cargo test --verbose --features "markdown pancurses-backend termion-backend crossterm-backend"
