[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
categories = ["command-line-interface", "gui"]
description = "A TUI (Text User Interface) library focused on ease-of-use."
documentation = "https://docs.rs/cursive"
exclude = ["doc/**", "assets/**", "examples/**"]
keywords = ["ncurses", "TUI", "UI"]
license = "MIT"
name = "cursive"
readme = "Readme.md"
repository = "https://github.com/gyscos/cursive"
version = "0.15.0-alpha.0"
edition = "2018"

[dependencies]
cursive_core = { path = "../cursive-core" }
crossbeam-channel = "0.4.0"
cfg-if = "0.1.9"
enumset = "1.0.0"
unicode-segmentation = "1.3.0"
unicode-width = "0.1.5"
lazy_static = "1"
libc = "0.2.60"
term_size = { version = "0.3", optional = true }
maplit = { version = "1.0", optional = true }
log = "0.4.8"
ahash = "0.3.2"

[dependencies.bear-lib-terminal]
optional = true
version = "2.0.0"

[dependencies.ncurses]
features = ["wide"]
optional = true
version = "5.99.0"

[dependencies.pancurses]
features = ["wide"]
optional = true
version = "0.16.1"

[dependencies.termion]
optional = true
version = "1.5.3"

[dependencies.crossterm]
optional = true
version = "0.17"

[dev-dependencies]
rand = "0.7.0"
pretty-bytes = "0.2.2"
atty = "0.2.13"

[features]
blt-backend = ["bear-lib-terminal"]
default = ["ncurses-backend"]
ncurses-backend = ["ncurses", "maplit", "term_size"]
pancurses-backend = ["pancurses", "maplit", "term_size"]
termion-backend = ["termion"]
crossterm-backend = ["crossterm"]
markdown = ["cursive_core/markdown"]
unstable_scroll = ["cursive_core/unstable_scroll"]

[lib]
name = "cursive"

[target.'cfg(unix)'.dependencies]
signal-hook = "0.1"
