[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
categories = ["command-line-interface", "gui"]
description = "Core components for the Cursive TUI"
documentation = "https://docs.rs/cursive"
exclude = ["doc/**", "assets/**", "examples/**"]
keywords = ["ncurses", "TUI", "UI"]
license = "MIT"
name = "cursive_core"
readme = "Readme.md"
repository = "https://github.com/gyscos/cursive"
version = "0.1.0"
edition = "2018"

[package.metadata.docs.rs]
features = ["unstable_scroll", "scroll", "markdown"]

[badges.travis-ci]
repository = "gyscos/cursive"

[badges.appveyor]
repository = "gyscos/cursive"

[dependencies]
enum-map = "0.6.0"
enumset = "1.0.0"
log = "0.4.8"
owning_ref = "0.4.0"
unicode-segmentation = "1.3.0"
unicode-width = "0.1.5"
xi-unicode = "0.2.0"
libc = "0.2.60"
crossbeam-channel = "0.4.0"
lazy_static = "1"
chrono = "0.4.7"
ahash = "0.3"

[dependencies.toml]
optional = true
version = "0.5.1"

[dependencies.num]
default-features = false
version = "0.2.0"

[dependencies.pulldown-cmark]
default-features = false
optional = true
version = "0.7.0"

[target.'cfg(unix)'.dependencies]
signal-hook = "0.1"

[dev-dependencies]
rand = "0.7.0"
pretty-bytes = "0.2.2"
atty = "0.2.13"

[features]
markdown = ["pulldown-cmark"]
unstable_scroll = []

[lib]
name = "cursive_core"
